
name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install llvm 16
      run: sudo apt-get purge --auto-remove llvm python3-lldb-14 llvm-14 && wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 16
    - name: Install litecoin for tests
      run: |
        tarball=litecoin.tar.gz
        wget -O "$tarball" https://download.litecoin.org/litecoin-0.21.2.2/linux/litecoin-0.21.2.2-x86_64-linux-gnu.tar.gz
        tar xvzf "$tarball"
        sudo cp -r litecoin-*/* /usr/local
    - name: Build contract
      run: make all
    - name: Run auth_rust tests
      run: cd tests/auth_rust && bash run.sh
    - name: Install ckb-debugger
      run: cd tests/auth_spawn_rust && make install
    - name: Run auth_spawn_rust tests
      run: cd tests/auth_spawn_rust && make all
    - name: Install cardano tools
      run: cd tests/cardano_lock && make install_cardano_tools
    - name: Run cardano tests
      run: cd tests/cardano_lock && make all
    - name: Run ckb-auth-cli tests
      run: cd tools/ckb-auth-cli && cargo test

